### ISSUE TITLE
Double mouse pointer in F11 menu

### ISSUE THREAD

**Issue by lucifer602288** [Shoun2137/GD3D11#2]
In the F11 menu on Windows the mouse pointer is two times displayed. Only one mouse pointer is the real to click the buttons.

**Comment by Shoun2137** [comment]
This was done on purpose, because in non-native res the mouse cursor is not aligned 1:1 to the custom UIs, i'll prolly come up with some better way to handle stuff, but for now, its the sane thing to do.

**Comment by lucifer602288** [comment]
Thanks for the new UI.

**Comment by Shoun2137** [comment]
Fixed in next release.

**Comment by lucifer602288** [comment]
When will next release be available?
